/** ローカル版の初期表示専用。新しいクラウドアカウントには登録しません。 */
export const ownedPeg = {
  id: "owned-b08xldyzc5",
  name: "V字型チタンペグ 16cm",
  category: "工具・ロープ",
  brand: "TITAN MANIA",
  qty: 6,
  qtyUnit: "本",
  weight: 0.012,
  status: "check",
  default: false,
  storage: "",
  purchased: "",
  url: "https://www.amazon.co.jp/dp/B08XLDYZC5",
  photoSrc: "assets/owned-gear/titanmania-v-pegs-cutout.webp",
  photoCutout: true,
  note: "添付写真をもとに試し登録。穴ありのV字型・オレンジ色のロープ付き。\n商品仕様はTITAN MANIA公式の16cmタイプを参照：チタン製、約15×160mm、1本約12g、6本セット・収納袋付き。Amazonページとの照合は未確認。\n所持本数は写真の6本で仮登録。購入日・保管場所・現在の状態は未確認。",
  updated: Date.now(),
};

export const sample = {
  theme: "light",
  trip: {
    name: "次回キャンプ",
    selected: ["g1", "g2", "g4", "g6", "g8", "g12"],
  },
  gear: [
    ownedPeg,
    {
      id: "g1",
      name: "LEDランタン",
      category: "照明・電源",
      brand: "Goal Zero",
      qty: 2,
      weight: 0.35,
      status: "check",
      default: true,
      storage: "収納BOX A",
      purchased: "2025-08-22",
      url: "",
      note: "出発前に充電確認",
      updated: 19,
    },
    {
      id: "g2",
      name: "マグカップ",
      category: "調理・食器",
      brand: "Snow Peak",
      qty: 2,
      weight: 0.18,
      status: "good",
      default: true,
      storage: "収納BOX A",
      purchased: "2025-02-10",
      url: "",
      note: "お気に入りのカップ",
      updated: 18,
    },
    {
      id: "g3",
      name: "クッカーセット",
      category: "調理・食器",
      brand: "UNIFLAME",
      qty: 1,
      weight: 1.1,
      status: "good",
      default: true,
      storage: "収納BOX C",
      purchased: "2024-11-02",
      url: "",
      note: "フライパン・鍋のセット",
      updated: 17,
    },
    {
      id: "g4",
      name: "テント 2ルーム",
      category: "テント・タープ",
      brand: "Coleman",
      qty: 1,
      weight: 16,
      status: "good",
      default: true,
      storage: "物置 / 大型棚",
      purchased: "2024-05-11",
      url: "",
      note: "インナー含む",
      updated: 16,
    },
    {
      id: "g5",
      name: "シュラフ",
      category: "寝具",
      brand: "mont-bell",
      qty: 2,
      weight: 1.2,
      status: "good",
      default: true,
      storage: "収納BOX B",
      purchased: "2024-10-01",
      url: "",
      note: "",
      updated: 15,
    },
    {
      id: "g6",
      name: "クーラーボックス",
      category: "クーラー・保冷",
      brand: "Coleman",
      qty: 1,
      weight: 4.6,
      status: "good",
      default: true,
      storage: "物置 / 下段",
      purchased: "2023-06-10",
      url: "",
      note: "保冷剤も確認",
      updated: 14,
    },
    {
      id: "g7",
      name: "ロープセット",
      category: "工具・ロープ",
      brand: "",
      qty: 1,
      weight: 0.8,
      status: "good",
      default: true,
      storage: "収納BOX C",
      purchased: "",
      url: "",
      note: "自在金具入り",
      updated: 13,
    },
    {
      id: "g8",
      name: "キャンプリュック",
      category: "その他",
      brand: "",
      qty: 1,
      weight: 1.8,
      status: "good",
      default: false,
      storage: "玄関収納",
      purchased: "",
      url: "",
      note: "小物の運搬用",
      updated: 12,
    },
    {
      id: "g9",
      name: "ペグハンマー",
      category: "工具・ロープ",
      brand: "Snow Peak",
      qty: 1,
      weight: 0.67,
      status: "good",
      default: true,
      storage: "ペグケース",
      purchased: "2025-03-13",
      url: "",
      note: "",
      updated: 11,
    },
    {
      id: "g10",
      name: "鍛造ペグ 30cm",
      category: "工具・ロープ",
      brand: "",
      qty: 20,
      weight: 0.16,
      status: "check",
      default: true,
      storage: "ペグケース",
      purchased: "",
      url: "",
      note: "本数確認",
      updated: 10,
    },
    {
      id: "g11",
      name: "救急セット",
      category: "衛生・救急",
      brand: "",
      qty: 1,
      weight: 0.45,
      status: "good",
      default: true,
      storage: "車載BOX",
      purchased: "",
      url: "",
      note: "",
      updated: 9,
    },
    {
      id: "g12",
      name: "ガスバーナー",
      category: "焚き火・火器",
      brand: "SOTO",
      qty: 1,
      weight: 0.35,
      status: "good",
      default: true,
      storage: "調理BOX",
      purchased: "2024-07-09",
      url: "",
      note: "",
      updated: 8,
    },
    {
      id: "g13",
      name: "ポータブル電源",
      category: "照明・電源",
      brand: "EcoFlow",
      qty: 1,
      weight: 7.8,
      status: "repair",
      default: false,
      storage: "室内保管",
      purchased: "2024-01-16",
      url: "",
      note: "DC出力確認",
      updated: 7,
    },
    {
      id: "g14",
      name: "インフレーターマット",
      category: "寝具",
      brand: "WAQ",
      qty: 2,
      weight: 2.8,
      status: "good",
      default: true,
      storage: "収納BOX B",
      purchased: "2025-04-20",
      url: "",
      note: "",
      updated: 6,
    },
    {
      id: "g15",
      name: "ジャケット",
      category: "衣類",
      brand: "",
      qty: 1,
      weight: 0.9,
      status: "good",
      default: false,
      storage: "衣類ラック",
      purchased: "",
      url: "",
      note: "寒い時用",
      updated: 5,
    },
  ],
};
